---
- name: Create src directory
  file: path={{ src_dir }} state=directory

- name: Ensure that tomcat_dir is there
  file: path="{{tomcat_dir}}" state=directory

- name: Check if tomcat_install_file exists
  local_action: stat path={{tomcat_install_file}}
  register: tomcat_install_file_exists

- name: Download Tomcat
  get_url: url=http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.56/bin/apache-tomcat-7.0.56.tar.gz dest="{{ tomcat_install_file }}" sha256sum=c0ca44be20bccebbb043ccd7ab5ea4d94060fdde6bb84812f3da363955dae5bb
  when: tomcat_install_file_exists != true
  
- name: Extract archive
  shell: tar -xzvf {{tomcat_install_file}} --strip-components=1 chdir="{{ tomcat_dir }}"

- name: Configure Tomcat-users.xml
  template: src=tomcat-users.xml dest="{{ tomcat_dir }}/conf/tomcat-users.xml"

- name: Configure Tomcat server.xml
  template: src=server.xml.j2 dest="{{ tomcat_dir }}/conf/server.xml"
