---
- name: Clone WP
  git: repo=https://github.com/OpenDevelopmentMekong/odm-frontend.git
         dest="{{wp_dir}}/"
         force=yes
         recursive=yes

- name: Copy config.php file
  template: src=wp-config.php.j2 dest="{{wp_dir}}/wp-config.php"

- name: Copy .htaccess file
  template: src=wp-htaccess.j2 dest="{{wp_dir}}/.htaccess"

- name: Remove index.html
  file: path="{{wp_dir}}/index.html" state=absent
