---
- name: Clone WP
  git: repo=https://github.com/OpenDevelopmentMekong/WordPress.git
         dest="{{wp_dir}}/"
         version=4.0
         force=yes

- name: Copy config.php file
  template: src=wp-config.php.j2 dest="{{wp_dir}}/wp-config.php"

- name: Clone wpckan plugin
  git: repo=https://github.com/OpenDevelopmentMekong/wpckan.git
         dest="{{wp_dir}}/wp-content/plugins/wpckan"
         version=wpckan-0.9.1
         force=yes
         recursive=yes

- name: Clone mqtranslate plugin
  git: repo=https://github.com/OpenDevelopmentMekong/mqtranslate.git
         dest="{{wp_dir}}/wp-content/plugins/mqtranslate"
         version=2.9
         force=yes
         recursive=yes

- name: Remove index.html
  file: path="{{wp_dir}}/index.html" state=absent
