---
- name: Stop CKAN
  shell: source {{ckan_env}}/bin/activate && {{supervisor_bin}}/supervisorctl stop ckan executable=/bin/bash

- name: Ensure that ckan_src is there
  file: path="{{ckan_src}}" state=directory

- name: Checkout CKAN (ODM fork) from git
  git: repo=https://github.com/OpenDevelopmentMekong/ckan-2.3.git
         dest="{{ckan_src}}"
         version=master

- name: install pip
  easy_install: name=pip executable=easy_install-2.7

- name: install virtualenv
  easy_install: name=virtualenv executable=easy_install-2.7

- name: Install CKAN dependencies
  pip: requirements={{ckan_src}}/requirements.txt virtualenv="{{virtual_envs}}/ckan"

- name: Install CKAN dependencies for testing
  pip: requirements={{ckan_src}}/dev-requirements.txt virtualenv="{{virtual_envs}}/ckan"

- name: Install CKAN
  pip: name="{{ckan_src}}/." virtualenv="{{virtual_envs}}/ckan"

- name: Create ckan etc default
  file: path="{{ ckan_etc }}/default" state=directory

- name: Remove development.ini
  file: path="{{ckan_ini}}" state=absent

- name: Generate development.ini
  shell: source {{ckan_env}}/bin/activate && paster make-config ckan {{ckan_ini}} executable=/bin/bash

- name: Edit development.ini
  ini_file: dest="{{ckan_ini}}"
              section=server:main
              option=host
              value=0.0.0.0

- ini_file: dest="{{ckan_ini}}"
              section=server:main
              option=port
              value="{{ckan_port}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=sqlalchemy.url
              value=postgresql://ckan_default:ckan_test1@localhost/ckan_default

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.datastore.write_url
              value=postgresql://ckan_default:ckan_test1@localhost/datastore_default

# Commented to enable legacy mode and solve set-permission.sql not found issue
# - ini_file: dest="{{ckan_ini}}"
#               section=app:main
#               option=ckan.datastore.read_url
#               value=postgresql://datastore_default:ckan_test1@localhost/datastore_default

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=solr_url
              value="{{solr_url}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.datapusher.url
              value="{{datapusher_url}}:{{datapusher_port}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.storage_path
              value="{{ckan_env}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.site_url
              value="{{ckan_url}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.plugins
              value="stats image_view text_view webpage_view recline_view recline_grid_view recline_graph_view recline_map_view pdf_view datastore datapusher resource_proxy odm_theme geo_view geojson_view googleanalytics"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.views.default_views
              value="image_view text_view webpage_view recline_view recline_grid_view recline_graph_view recline_map_view pdf_view geo_view geojson_view"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckanext.geoview.ol_viewer.formats
              value="wms kml gml wfs arcgis_rest"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.locales_offered
              value="vi km en th"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.auth.anon_create_dataset
              value="false"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.auth.create_unowned_dataset
              value="false"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.auth.create_dataset_if_not_in_organization
              value="false"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.auth.user_create_groups
              value="false"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.auth.user_create_organizations
              value="false"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.auth.user_delete_groups
              value="false"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.auth.user_delete_organizations
              value="false"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.activity_streams_email_notifications
              value="True"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=smtp.mail_from
              value="{{email_account}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=smtp.server
              value="{{email_server}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=smtp.starttls
              value="True"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=smtp.user
              value="{{email_user}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=smtp.starttls
              value="{{email_password}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=googleanalytics.id
              value="{{googleanalytics_id}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=googleanalytics.account
              value="{{googleanalytics_account}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=googleanalytics.username
              value="{{googleanalytics_username}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=googleanalytics.password
              value="{{googleanalytics_password}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=licenses_group_url
              value="{{ckan_licenses_url}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.favicon
              value="{{ckan_favicon_url}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.resource_proxy.max_file_size
              value="52428800"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.max_resource_size
              value="50"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.cors.origin_allow_all
              value="False"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.cors.origin_whitelist
              value="http://opendevelopmentmekong.net http://cambodia.opendevelopmentmekong.net http://vietnam.opendevelopmentmekong.net http://laos.opendevelopmentmekong.net http://myanmar.opendevelopmentmekong.net http://thailand.opendevelopmentmekong.net/"

- name: Create cron job for sending out email notifications
  cron: name="Schedule email notifications" special_time="hourly" job="source {{ckan_env}}/bin/activate && echo '{}' | paster --plugin=ckan post -c {{ckan_ini}} /api/action/send_email_notifications > /dev/null" state="present"

- name: Link who.ini
  file: src="{{ckan_env}}/lib/{{ansible_python_interpreter}}/site-packages/ckan/config/who.ini" dest="{{ ckan_etc }}/default/who.ini" state=link

- name: Install CKAN Api
  pip: name="git+https://github.com/ckan/ckanapi.git@ckanapi-3.3#egg=ckanapi" virtualenv="{{virtual_envs}}/ckan"

- name: CKAN Api Develop
  shell: source {{ckan_env}}/bin/activate && python setup.py develop executable=/bin/bash
  args:
    chdir: "{{virtual_envs}}/ckan/src/ckanapi"

- name: Install ckanext-odm_theme
  file: path="{{ ckan_env }}/src/ckanext-odm_theme" state=directory

- git: repo=https://github.com/OpenDevelopmentMekong/ckanext-odm_theme.git
        dest="{{ ckan_env }}/src/ckanext-odm_theme"
        version=master

- shell: source {{ckan_env}}/bin/activate && python setup.py develop executable=/bin/bash
  args:
    chdir: "{{ ckan_env }}/src/ckanext-odm_theme"

- name: Install ckanext-odm_theme extension dependencies
  pip: requirements="{{ ckan_env }}/src/ckanext-odm_theme/requirements.txt" virtualenv="{{virtual_envs}}/ckan"

- name: Install ckanext-odm_theme extension dependencies (development)
  pip: requirements="{{ ckan_env }}/src/ckanext-odm_theme/dev-requirements.txt" virtualenv="{{virtual_envs}}/ckan"

- name: Install Datapusher extension
  git: repo=https://github.com/ckan/datapusher.git version=stable
        dest="{{ ckan_env }}/src/datapusher"

- pip: requirements="{{ckan_env}}/src/datapusher/requirements.txt" extra_args="-e {{ckan_env}}/src/datapusher/" virtualenv="{{virtual_envs}}/ckan"

- name: Remove datapusher_settings.py, will be copied in the next step
  file: path="{{ckan_env}}/src/datapusher/deployment/datapusher_settings.py" state=absent

- name: Copy datapusher_settings.py Template over
  template: src=datapusher_settings.py dest={{ckan_env}}/src/datapusher/deployment/datapusher_settings.py

- name: Install pdfview extension
  file: path="{{ ckan_env }}/src/ckanext-pdfview" state=directory

- git: repo=https://github.com/ckan/ckanext-pdfview.git
        dest="{{ ckan_env }}/src/ckanext-pdfview"
        version=master

- shell: source {{ckan_env}}/bin/activate && python setup.py develop executable=/bin/bash
  args:
    chdir: "{{ ckan_env }}/src/ckanext-pdfview"

- name: Install ckanext-geoview extension (Just for Preview for spatial formats)
  pip: name="git+https://github.com/ckan/ckanext-geoview.git#egg=ckanext-geoview" virtualenv="{{virtual_envs}}/ckan"

- name: Install  ckanext-spatial extension dependencies
  pip: requirements={{ckan_env}}/src/ckanext-geoview/pip-requirements.txt virtualenv="{{virtual_envs}}/ckan"

- shell: source {{ckan_env}}/bin/activate && python setup.py develop executable=/bin/bash
  args:
    chdir: "{{ ckan_env }}/src/ckanext-geoview"

- name: Install Google Analytics extension
  pip: name="git+https://github.com/ckan/ckanext-googleanalytics.git#egg=ckanext-googleanalytics" virtualenv="{{virtual_envs}}/ckan"

- shell: source {{ckan_env}}/bin/activate && python setup.py develop executable=/bin/bash
  args:
    chdir: "{{ ckan_env }}/src/ckanext-googleanalytics"

- name: Initialize database
  shell: source {{ckan_env}}/bin/activate && paster --plugin=ckan db init --config={{ckan_ini}} executable=/bin/bash

# Uncomment when legacy mode is disabled
# - name: Setup the DataStore
#   shell: source {{ckan_env}}/bin/activate && paster --plugin=ckan datastore set-permissions postgres --config={{ckan_ini}}

- name: Start CKAN
  shell: source {{ckan_env}}/bin/activate && {{supervisor_bin}}/supervisorctl start ckan executable=/bin/bash

- name: Start datapusher
  shell: source {{ckan_env}}/bin/activate && {{supervisor_bin}}/supervisorctl start datapusher executable=/bin/bash
