---
- name: apache-start
  service:
    name=apache2
    start=started
  sudo: yes

- name: apache-stop
  service:
    name=apache2
    start=stopped
  sudo: yes

- name: apache-reload
  service:
    name=apache2
    state=reloaded
  sudo: yes

- name: apache-restart
  service:
    name=apache2
    state=restarted
  sudo: yes
