---
# Based on instructions from http://martinbrochhaus.com/solr.html
- name: Install Supervisord
  pip: name="supervisor"
  
- name: Create the cron log directory
  file: path="{{home_dir}}/logs/user/cron" state=directory

- name: Create the temp directory
  file: path="{{home_dir}}/tmp" state=directory

- name: Create the etc directory
  file: path="{{home_dir}}/etc" state=directory

- name: Copy Template over
  template: src=supervisord.conf.j2 dest={{home_dir}}/etc/supervisord.conf
  
- name: Add supervisord to cron
  cron: name="supervisord" minute="*/5" job="{{home_dir}}/bin/supervisord > {{home_dir}}/logs/user/cron/supervisord.log 2>&1"

- name: Run supervisord
  shell: "{{home_dir}}/bin/supervisord > {{home_dir}}/logs/user/cron/supervisord.log 2>&1"