---
- name: Stop CKAN
  command: supervisorctl stop ckan
  
- name: Checkout CKAN 2.2 from git
  git: repo=https://github.com/ckan/ckan.git
         dest="{{ckan_src}}"
         version=ckan-2.2

- name: Download patch for CKAN
  get_url: url=https://github.com/ckan/ckan/commit/fa60dc947eb6db612218d8d89affec7d6df3b096.patch dest="{{src_dir}}/ckan_fix.patch"

- name: Patch CKAN
  command: git apply {{src_dir}}/ckan_fix.patch
  args:
    chdir: "{{ckan_src}}"

- name: install pip
  easy_install: name=pip executable=easy_install-2.7

- name: install virtualenv
  easy_install: name=virtualenv executable=easy_install-2.7

- name: Install CKAN dependencies
  pip: requirements={{ckan_src}}/requirements.txt virtualenv="{{virtual_envs}}/ckan"

- name: Install CKAN
  pip: name="{{ckan_src}}/." virtualenv="{{virtual_envs}}/ckan"

- name: Create ckan etc default
  file: path="{{ ckan_etc }}/default" state=directory

- name: Remove development.ini
  file: path="{{ckan_ini}}" state=absent

- name: Generate development.ini
  shell: source {{ckan_env}}/bin/activate && paster make-config ckan {{ckan_ini}}
  
- name: Edit development.ini
  ini_file: dest="{{ckan_ini}}"
              section=server:main
              option=host
              value=127.0.0.1

- ini_file: dest="{{ckan_ini}}"
              section=server:main
              option=port
              value="{{ckan_port}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=sqlalchemy.url
              value=postgresql://ckan_default:ckan_test1@localhost/ckan_default

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=solr_url
              value="{{solr_url}}"

- ini_file: dest="{{ckan_ini}}"
              section=app:main
              option=ckan.site_url
              value="{{ckan_url}}"

- name: Link who.ini
  file: src="{{ckan_env}}/lib/python2.7/site-packages/ckan/config/who.ini" dest="{{ ckan_etc }}/default/who.ini" state=link

- name: Initialize database
  shell: source {{ckan_env}}/bin/activate && paster --plugin=ckan db init --config={{ckan_ini}}

- name: Start CKAN
  command: supervisorctl start ckan