---
- name: Install required packages.
  action: apt pkg={{ item }} state=present
  sudo: yes
  with_items:
    - apache2
    - libapache2-mod-wsgi
    - mysql-server-5.5
    - mysql-server
    - php5
    - php5-mysql
    - php5-curl
    - python-mysqldb
    - git-core
    - dnsmasq

- name: Create DB User
  mysql_user: name={{wp_db_user}} password={{wp_db_password}} priv=*.*:ALL state=present
  sudo: yes

- name: Drop DB (if exists)
  mysql_db: name={{wp_db_name}} login_user={{wp_db_user}} login_password={{wp_db_password}} state=absent
  sudo: yes

- name: Create DB
  mysql_db: name={{wp_db_name}} login_user={{wp_db_user}} login_password={{wp_db_password}} state=present
  sudo: yes

- name: Add vhost configuration file to sites-available
  template: src=wp.vagrantbox.conf.j2 dest=/etc/apache2/sites-available/wp.vagrantbox.conf
  sudo: yes

- name: Disable default site
  command: a2dissite 000-default
  sudo: yes

- name: Enable our new site
  command: a2ensite wp.vagrantbox
  sudo: yes

# phpmyadmin

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'
  sudo: yes

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='{{wp_db_password}}' vtype='password'
  sudo: yes

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='{{wp_db_password}}' vtype='password'
  sudo: yes

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='{{wp_db_password}}' vtype='password'
  sudo: yes

- name: debconf for pma
  debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='' vtype='multiselect'
  sudo: yes
#
- name: Enable mod_rewrite
  shell: a2enmod rewrite
  sudo: yes

- name: Restart apache
  service: name=apache2 state=restarted
  sudo: yes

# - name: Add entry into hosts file
#   lineinfile: dest=/etc/hosts
#               regexp='^'
#               line='127.0.0.1 {{wp_domain}}'
#               state=present
#   sudo: yes

- name: Ensure that wp directory is present
  file: path="{{wp_dir}}" state=directory

- name: Enable wildcard for dnsmasq
  lineinfile: dest=/etc/dnsmasq.conf
              regexp='^'
              line='address=/.{{wp_domain}}/127.0.0.1'
              state=present
  sudo: yes

- name: Restart dnsmasq
  service: name=dnsmasq state=restarted
  sudo: yes
