---
- name: add new sources.list that checks for mirror
  copy: src=sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644
  sudo: yes
  
- name: Update package list
  apt: update_cache=yes
  sudo: yes