---
- name: Install python-pip
  apt: name=python-pip state=present
  sudo: yes

- name: install pip
  easy_install: name=pip executable=easy_install-2.7
  sudo: yes

- name: install virtualenv
  easy_install: name=virtualenv executable=easy_install-2.7
  sudo: yes

- name: Install required packages.
  action: apt pkg={{ item }} state=present
  sudo: yes
  with_items:
    - git-core
    - libxslt-dev
    - libxslt1.1
    - libxml2
    - libxml2-dev
    - python-libxml2
    - python-libxslt1
    - libssl-dev
    - build-essential
    - python-dev
    - postgresql
    - libpq-dev
    - libpq5
    - zlib1g-dev
    - python-setuptools
    - openjdk-6-jdk
    - python-psycopg2
    - apache2
    - libgeos-dev
    - libmagickwand-dev
    - python-jinja2

- name: Create virtualenv
  shell: virtualenv --no-site-packages {{virtual_envs}}/ckan

- name: Install lxml
  shell: source {{virtual_envs}}/ckan/bin/activate && CFLAGS="-O0" pip install lxml executable=/bin/bash
  sudo: yes

- name: Replace pg_hba.conf
  template: src=pg_hba.conf.j2 dest="{{pg_main}}/pg_hba.conf"
  sudo: yes

- name: Restart postgresql
  service: name=postgresql state=restarted
  sudo: yes

- name: Setup database (ckan_default)
  postgresql_user: name=ckan_default password=ckan_test1 role_attr_flags=SUPERUSER

- name: Setup databases and users (ckan_default)
  postgresql_db: name=ckan_default owner=ckan_default encoding='UTF-8' state=present

- name: Setup database (datastore_default)
  postgresql_db: name=datastore_default owner=ckan_default encoding='UTF-8' state=present

- name: Setup database users (datastore_default)
  postgresql_user: name=datastore_default password=ckan_test1 db=datastore_default role_attr_flags=NOSUPERUSER

- name: Setup databases and users (ckan_test)
  postgresql_db: name=ckan_test owner=ckan_default encoding='UTF-8' state=present

- name: Setup databases and users (datastore_test)
  postgresql_db: name=datastore_test owner=ckan_default encoding='UTF-8' state=present
