---
# Description: Create a new Apache virtual hosts
# Original from: https://github.com/gaspaio/ansible-devbox/blob/master/roles/apache/tasks/vhost_add.yml
#
# Parameters:
# - {{ vhosts }} : Virtual hosts hash. See defaults/main.yml


- name: Change default virtual host to given vhost and port
  lineinfile:
    dest={{ apache.default_vhost_path }}
    regexp='^\<VirtualHost'
    line="<VirtualHost {{ apache.listen|join(' ') }}>"
  sudo: yes
  notify: apache-reload

- name: Disabling virtual hosts
  command:
    a2dissite {{ item.key }}.conf
    removes=/etc/apache2/sites-enabled/{{ item.key }}.conf
  with_dict: vhosts
  sudo: yes
  notify: apache-reload
  when: "not item.value.enabled|bool"

- name: Removing virtual hosts
  command:
    rm /etc/apache2/sites-available/{{ item.key }}.conf
    removes=/etc/apache2/sites-available/{{ item.key }}.conf
  with_dict: vhosts
  sudo: yes
  notify: apache-reload
  when: "not item.value.enabled|bool"

- name: Adding virtual hosts
  template:
    src=vhost.conf.j2
    dest=/etc/apache2/sites-available/{{ item.key }}.conf
    mode=0644
  with_dict: vhosts
  sudo: yes
  notify: apache-reload
  when: item.value.enabled|bool

- name: Enabling virtual hosts
  command:
    a2ensite {{ item.key }}.conf
    creates=/etc/apache2/sites-enabled/{{ item.key }}.conf
  with_dict: vhosts
  sudo: yes
  notify: apache-reload
  when: item.value.enabled|bool
